[versions]
binary-compatibility-validator = "0.18.0"
fabric-loom = "1.4.5"
forgegradle = "6.0.26"
gradle-toolchain-switches = "0.3.0"
gradle-shadow = "8.3.8"
kotlin = "2.2.0"
kotlinx-serialization = "1.5.0"
ktor = "2.3.13"
junit = "5.13.2"
moddevgradle = "1.0.19"
neogradle = "7.0.61"
nokee-gradle-plugin-dev = "1.6.10"
plugin-publish = "1.3.1"


[libraries]
# net.fabricmc:fabric-loom - Fabric Loom
# https://github.com/FabricMC/fabric-loom
fabric-loom = { module = "net.fabricmc:fabric-loom", version.ref = "fabric-loom" }

# io.ktor - Ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

# net.minecraftforge.gradle - ForgeGradle
# https://github.com/MinecraftForge/ForgeGradle
forgegradle = { module = "net.minecraftforge.gradle:ForgeGradle", version.ref = "forgegradle" }

# net.neoforged.gradle.userdev - NeoGradle
# https://github.com/neoforged/NeoGradle
neogradle = { module = "net.neoforged.gradle:userdev", version.ref = "neogradle" }

# net.neoforged:moddev-gradle - ModDevGradle
# https://github.com/neoforged/ModDevGradle
moddevgradle = { module = "net.neoforged:moddev-gradle", version.ref = "moddevgradle" }

# org.jetbrains.kotlinx:kotlinx-serialization-* - kotlinx-serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.junit - JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }


[plugins]
# com.gradle.plugin-publish - plugin-publish
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }

# com.github.johnrengelman.shadow - Gradle Shadow
# https://github.com/Goooler/shadow (https://github.com/GradleUp/shadow)
#gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }

# dev.gradleplugins - Nokee Gradle Plugin Development Plugins
# https://github.com/gradle-plugins/toolbox
java-gradle-plugin = { id = "dev.gradleplugins.java-gradle-plugin", version.ref = "nokee-gradle-plugin-dev" }

# io.github.themrmilchmann.gradle.toolchainswitches:gradle-toolchain-switches - Gradle Toolchain Switches Plugin
gradle-toolchain-switches = { id = "io.github.themrmilchmann.toolchain-switches", version.ref = "gradle-toolchain-switches" }

# org.jetbrains.kotlinx.binary-compatibility-validator - binary-compatibility-validator
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }

# org.jetbrains.kotlin - Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-samwithreceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }