[versions]
gradle-shadow = "7.1.2"
kotlin = "1.5.31"
kotlinx-serialization = "1.3.2"
ktor = "1.6.7"
plugin-publish = "0.20.0"
spock = "2.0-groovy-3.0"

[libraries]
# io.ktor - Ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }

# org.jetbrains.kotlinx:kotlinx-serialization-* - kotlinx-serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.spockframework - Spock
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }

[plugins]
# com.github.johnrengelman.shadow - Gradle Shadow
gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }

# com.gradle.plugin-publish - plugin-publish
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }

# org.jetbrains.kotlin - Kotlin
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }